import { Ingredient } from '../types';

export interface PackageItem {
  name: string;
  quantity: number;
  unit: string;
  category: Ingredient['category'];
  storage_type: Ingredient['storage_type'];
}

export interface IngredientPackage {
  id: string;
  emoji: string;
  title: string;
  description: string;
  tag: string;
  tagColor: string;
  tagBg: string;
  items: PackageItem[];
}

export const PRESET_PACKAGES: IngredientPackage[] = [
  {
    id: 'korean_basic',
    emoji: '🥢',
    title: '한식 기본 재료',
    description: '된장찌개, 볶음밥, 계란말이 등 기본 한식 요리에 필요한 재료들',
    tag: '가장 많이 추가',
    tagColor: '#3182F6',
    tagBg: '#EBF3FF',
    items: [
      { name: '국간장', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '진간장', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '고추장', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '된장', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '쌈장', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '고춧가루', quantity: 1, unit: '봉지', category: 'condiment', storage_type: 'room_temp' },
      { name: '다진마늘', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '다진생강', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '참기름', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '참깨', quantity: 1, unit: '봉지', category: 'condiment', storage_type: 'room_temp' },
      { name: '들기름', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '식용유', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '멸치액젓', quantity: 1, unit: '병', category: 'condiment', storage_type: 'fridge' },
      { name: '참치액', quantity: 1, unit: '병', category: 'condiment', storage_type: 'fridge' },
      { name: '새우젓', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '다시마', quantity: 1, unit: '봉지', category: 'condiment', storage_type: 'room_temp' },
      { name: 'MSG', quantity: 1, unit: '개', category: 'condiment', storage_type: 'room_temp' },
      { name: '맛술', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '미림', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '설탕', quantity: 1, unit: '개', category: 'condiment', storage_type: 'room_temp' },
      { name: '소금', quantity: 1, unit: '개', category: 'condiment', storage_type: 'room_temp' },
      { name: '후추', quantity: 1, unit: '개', category: 'condiment', storage_type: 'room_temp' },
      { name: '식초', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '물엿', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '양파', quantity: 3, unit: '개', category: 'vegetable', storage_type: 'room_temp' },
      { name: '마늘', quantity: 1, unit: '통', category: 'vegetable', storage_type: 'fridge' },
      { name: '대파', quantity: 1, unit: '묶음', category: 'vegetable', storage_type: 'fridge' },
      { name: '생강', quantity: 1, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '청양고추', quantity: 5, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '무', quantity: 1, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '감자', quantity: 3, unit: '개', category: 'vegetable', storage_type: 'room_temp' },
      { name: '계란', quantity: 10, unit: '개', category: 'dairy', storage_type: 'fridge' },
      { name: '김치', quantity: 1, unit: '봉지', category: 'processed', storage_type: 'fridge' },
    ],
  },
  {
    id: 'western_basic',
    emoji: '🍝',
    title: '양식 기본 재료',
    description: '파스타, 샐러드, 오믈렛 등 간단한 양식 요리에 필요한 재료들',
    tag: '양식',
    tagColor: '#F59E0B',
    tagBg: '#FFFBEB',
    items: [
      { name: '소금', quantity: 1, unit: '개', category: 'condiment', storage_type: 'room_temp' },
      { name: '후추', quantity: 1, unit: '개', category: 'condiment', storage_type: 'room_temp' },
      { name: '올리브유', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '발사믹', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '레몬즙', quantity: 1, unit: '병', category: 'condiment', storage_type: 'fridge' },
      { name: '버터', quantity: 1, unit: '개', category: 'dairy', storage_type: 'fridge' },
      { name: '우유', quantity: 1, unit: '개', category: 'dairy', storage_type: 'fridge' },
      { name: '생크림', quantity: 1, unit: '개', category: 'dairy', storage_type: 'fridge' },
      { name: '파마산치즈', quantity: 1, unit: '개', category: 'dairy', storage_type: 'fridge' },
      { name: '모짜렐라치즈', quantity: 1, unit: '개', category: 'dairy', storage_type: 'fridge' },
      { name: '계란', quantity: 6, unit: '개', category: 'dairy', storage_type: 'fridge' },
      { name: '마늘', quantity: 1, unit: '통', category: 'vegetable', storage_type: 'fridge' },
      { name: '양파', quantity: 2, unit: '개', category: 'vegetable', storage_type: 'room_temp' },
      { name: '토마토', quantity: 2, unit: '개', category: 'vegetable', storage_type: 'room_temp' },
      { name: '방울토마토', quantity: 1, unit: '팩', category: 'vegetable', storage_type: 'fridge' },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '버섯', quantity: 1, unit: '팩', category: 'vegetable', storage_type: 'fridge' },
      { name: '바질', quantity: 1, unit: '팩', category: 'vegetable', storage_type: 'fridge' },
      { name: '파슬리', quantity: 1, unit: '팩', category: 'vegetable', storage_type: 'fridge' },
      { name: '로즈마리', quantity: 1, unit: '팩', category: 'vegetable', storage_type: 'fridge' },
      { name: '타임', quantity: 1, unit: '팩', category: 'vegetable', storage_type: 'fridge' },
      { name: '토마토소스', quantity: 1, unit: '개', category: 'processed', storage_type: 'room_temp' },
      { name: '바질페스토', quantity: 1, unit: '개', category: 'processed', storage_type: 'fridge' },
      { name: '파스타면', quantity: 1, unit: '봉지', category: 'processed', storage_type: 'room_temp' },
    ],
  },
  {
    id: 'condiments',
    emoji: '🫙',
    title: '조미료/양념 모음',
    description: '어떤 요리든 기본이 되는 소스·양념류 한 번에 채우기',
    tag: '필수 기본',
    tagColor: '#10B981',
    tagBg: '#ECFDF5',
    items: [
      { name: '국간장', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '진간장', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '고추장', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '된장', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '쌈장', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '설탕', quantity: 1, unit: '개', category: 'condiment', storage_type: 'room_temp' },
      { name: '소금', quantity: 1, unit: '개', category: 'condiment', storage_type: 'room_temp' },
      { name: '후추', quantity: 1, unit: '개', category: 'condiment', storage_type: 'room_temp' },
      { name: '고춧가루', quantity: 1, unit: '봉지', category: 'condiment', storage_type: 'room_temp' },
      { name: '다진마늘', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '다진생강', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '참기름', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '식용유', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '올리브유', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '들기름', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '식초', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '맛술', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '미림', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '물엿', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '올리고당', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '알룰로스', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '꿀', quantity: 1, unit: '병', category: 'condiment', storage_type: 'room_temp' },
      { name: '케챱', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '마요네즈', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '돈까스소스', quantity: 1, unit: '개', category: 'condiment', storage_type: 'fridge' },
      { name: '굴소스', quantity: 1, unit: '병', category: 'condiment', storage_type: 'fridge' },
      { name: '멸치액젓', quantity: 1, unit: '병', category: 'condiment', storage_type: 'fridge' },
      { name: '참치액', quantity: 1, unit: '병', category: 'condiment', storage_type: 'fridge' },
      { name: '참깨', quantity: 1, unit: '봉지', category: 'condiment', storage_type: 'room_temp' },
      { name: '다시마', quantity: 1, unit: '봉지', category: 'condiment', storage_type: 'room_temp' },
      { name: 'MSG', quantity: 1, unit: '개', category: 'condiment', storage_type: 'room_temp' },
    ],
  },
  {
    id: 'meat_basic',
    emoji: '🥩',
    title: '육류 기본 모음',
    description: '볶음, 구이, 찌개 등 다양하게 활용할 수 있는 육류 기본 구성',
    tag: '단백질',
    tagColor: '#EF4444',
    tagBg: '#FEF2F2',
    items: [
      { name: '소고기', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '돼지고기', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '닭고기', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '닭가슴살', quantity: 2, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '닭다리살', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '삼겹살', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '항정살', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '목살', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '대패삼겹살', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '다진돼지고기', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '다진소고기', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '베이컨', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '햄', quantity: 1, unit: '개', category: 'meat', storage_type: 'fridge' },
      { name: '소세지', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '우삼겹', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '차돌박이', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '소갈비', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
      { name: '돼지갈비', quantity: 1, unit: '팩', category: 'meat', storage_type: 'fridge' },
    ],
  },
  {
    id: 'vegetable_basic',
    emoji: '🥦',
    title: '채소 기본 모음',
    description: '국물요리, 볶음, 샐러드에 두루 쓰이는 기본 채소 구성',
    tag: '채소',
    tagColor: '#10B981',
    tagBg: '#ECFDF5',
    items: [
      { name: '양파', quantity: 3, unit: '개', category: 'vegetable', storage_type: 'room_temp' },
      { name: '대파', quantity: 1, unit: '묶음', category: 'vegetable', storage_type: 'fridge' },
      { name: '마늘', quantity: 1, unit: '통', category: 'vegetable', storage_type: 'fridge' },
      { name: '생강', quantity: 1, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '당근', quantity: 2, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '감자', quantity: 3, unit: '개', category: 'vegetable', storage_type: 'room_temp' },
      { name: '고구마', quantity: 3, unit: '개', category: 'vegetable', storage_type: 'room_temp' },
      { name: '무', quantity: 1, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '배추', quantity: 1, unit: '통', category: 'vegetable', storage_type: 'fridge' },
      { name: '애호박', quantity: 1, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '청양고추', quantity: 5, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '버섯', quantity: 1, unit: '팩', category: 'vegetable', storage_type: 'fridge' },
      { name: '토마토', quantity: 2, unit: '개', category: 'vegetable', storage_type: 'room_temp' },
      { name: '방울토마토', quantity: 1, unit: '팩', category: 'vegetable', storage_type: 'fridge' },
      { name: '오이', quantity: 2, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '양배추', quantity: 1, unit: '통', category: 'vegetable', storage_type: 'fridge' },
    ],
  },
  {
    id: 'fruit_basic',
    emoji: '🍎',
    title: '과일 기본 모음',
    description: '간식, 주스, 디저트로 활용하기 좋은 제철 과일 구성',
    tag: '과일',
    tagColor: '#F59E0B',
    tagBg: '#FFFBEB',
    items: [
      { name: '사과', quantity: 3, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '바나나', quantity: 1, unit: '묶음', category: 'vegetable', storage_type: 'room_temp' },
      { name: '귤', quantity: 5, unit: '개', category: 'vegetable', storage_type: 'room_temp' },
      { name: '포도', quantity: 1, unit: '송이', category: 'vegetable', storage_type: 'fridge' },
      { name: '딸기', quantity: 1, unit: '팩', category: 'vegetable', storage_type: 'fridge' },
      { name: '키위', quantity: 3, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '수박', quantity: 1, unit: '통', category: 'vegetable', storage_type: 'fridge' },
      { name: '복숭아', quantity: 3, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '배', quantity: 2, unit: '개', category: 'vegetable', storage_type: 'fridge' },
      { name: '망고', quantity: 2, unit: '개', category: 'vegetable', storage_type: 'room_temp' },
      { name: '블루베리', quantity: 1, unit: '팩', category: 'vegetable', storage_type: 'fridge' },
    ],
  },
];
